### ISSUE TITLE
Localhost testing

### ISSUE THREAD

**Issue by nicooprat** [veliovgroup/ostrio-analytics#2] opened 2017-11-01 14:37 UTC
Is it possible to get this package to work on local environment for testing purposes? Tried to add a server on https://ostr.io/ like `http://127.0.0.1/` or `http://localhost/` but it's not permitted. Also thought about using a tunnel service like https://ngrok.com/ but I won't be able to prove ownership.

Thanks.

**Comment by dr-dimitru** [comment] 2017-11-05 22:36
Hello @nicooprat ,

This is not currently possible, perhaps we will add a "development" mode to control panel which will allow localhost requests.
Thank you for suggestion, marked as [enhancement].

I assume tunneling can be used with `meta` tag or file ownership confirmation.
What type of confirmation are you using?

**Comment by nicooprat** [comment] 2017-11-06 08:25
Oh right I didn't think of the meta tag verification. I'm using https://ngrok.com/. Will make some tests. Thanks.

**Comment by dr-dimitru** [comment] 2017-11-06 11:05
@nicooprat keep us updated on this one. Curious if `ngrok` will work with meta tag verification.

**Comment by nicooprat** [comment] 2017-11-06 21:33
Working 👍

**Comment by dr-dimitru** [comment] 2017-11-06 22:36
Awesome.
Feel free to reopen it in case if the issue still persists on your end.

**Comment by dr-dimitru** [comment] 2017-12-10 19:49
Reopened. We will add a "development" mode to control panel which will allow localhost requests.

**Comment by dr-dimitru** [comment] 2018-09-15 16:18
Hello @nicooprat ,

it's been a while, thank you a lot for the suggestion, this feature is live now! ❤️❤️❤️

![screen shot 2018-09-15 at 7 12 46 pm](https://user-images.githubusercontent.com/1686778/45588341-16f24880-b91c-11e8-855d-6f07729c578d.png)


Feel free to reopen it in case if the issue is still persists on your end.

**Closed as completed by dr-dimitru** 2018-09-15 16:18 UTC
Labels: enhancement
